# Generated by Django 2.1 on 2019-06-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
