# Generated by Django 2.1 on 2019-06-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_total_views_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='total_views_counts',
            new_name='views_counts',
        ),
    ]
