# Generated by Django 2.1.5 on 2019-10-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190620_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-views_counts',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
